language: generic

git:
  depth: 5

services:
  - docker

before_install:
  - pip install --user pytidylib
  - git clone --branch 5.6.0 --depth=1 https://github.com/htacg/tidy-html5.git && ( cd tidy-html5 && cmake . && make && sudo make install )
  - sudo ldconfig
  - docker pull openmodelica/openmodelica:v1.12.0-minimal
  - docker pull openmodelica/moparser:3.4

script:
  - python .travis.py tidyHTML ./
  - python .travis.py checkHTML ./
  - docker run -v "$PWD:/repo" -w "/repo" openmodelica/openmodelica:v1.12.0-minimal omc .travis.mos
  - "! find . -name '*.mo' -exec bash -c 'iconv -o /dev/null -f utf8 -t utf8 \"{}\" |& sed \"s,^,{}: ,\"' ';' | grep '.'"
  - docker run -v "$PWD:/repo" -w "/repo" openmodelica/moparser:3.4 moparser -v 3.4 -r Complex.mo Modelica ModelicaReference ModelicaServices ModelicaTest ModelicaTestConversion4.mo ModelicaTestOverdetermined.mo ObsoleteModelica4.mo

notifications:
  email: false
