name: GenerateReleaseNotes

on:
  workflow_dispatch:
    inputs:
      milestone:
        description: 'Milestone number of the release'
        default: '61'
        required: true
      version:
        description: 'Version of the release'
        default: '4.1.0'
        required: true
      watermark:
        description: 'PDF contains watermark for test'
        default: true
        required: true
        type: boolean

jobs:
  generate_release_notes:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install python packages
        run: pip install --disable-pip-version-check --user docraptor==3.0.0 Jinja2==3.1.2 Markdown==3.4.4 requests PyYAML==6.0.1
      - name: Generate MSL release notes from closed GitHub issues
        timeout-minutes: 3
        env:
          DOCRAPTOR_API_KEY: ${{ secrets.DOCRAPTOR_API_KEY }}
          DOCRAPTOR_TEST: ${{ github.event.inputs.watermark }}
        run: python ./Modelica/Resources/Documentation/Generate-ReleaseNotes.py ${{ github.event.inputs.milestone }} ${{ github.event.inputs.version }}
      - uses: actions/upload-artifact@v3
        with:
          name: ResolvedGitHubIssues-Version-${{ github.event.inputs.version }}
          path: ./Modelica/Resources/Documentation/Version-${{ github.event.inputs.version }}/
